<?php
$value = array (
  'companyname' => 'Chọn Giá Tốt',
  'address' => 'Số 15, Giáp Nhất, Thanh Xuân, Hà Nội',
  'tel' => '0988.484.694',
  'hotline' => '0966.383.468',
  'cskh' => '0966.383.468',
  'tongdai1' => '',
  'tongdai2' => '',
  'tgphucvu' => '0966.383.468',
  'fax' => '',
  'email' => 'chongiatot68@gmail.com',
  'sitename' => 'Chọn Giá Tốt',
  'sitetitle' => 'Cửa hàng Chọn giá tốt - Sản phẩm tốt nhất trong tầm tay của bạn',
  'description' => 'Cửa hàng Chọn giá tốt - Sản phẩm tốt nhất trong tầm tay của bạn',
  'keyword' => 'chongiatot, nhân sâm, hồng sâm, linh chi, đông trùng hạ thảo',
  'abbreviation' => 'Chọn Giá Tốt',
  'tenngan' => 'Chọn Giá Tốt',
  'keywordseo' => 'Chọn Giá Tốt',
  'couponname' => 'Coupon',
  'currency' => 'đ',
  'currencyname' => 'VNĐ',
  'twitter' => '',
  'facebook' => 'https://www.facebook.com/chongiatot.vn',
  'youtube' => '',
  'googleplus' => '',
  'zingme' => '',
  'ym1' => 'chongiatot',
  'ym2' => '',
  'ym3' => '',
  'ym4' => '',
  'sk1' => 'chongiatot',
  'sk2' => '',
  'ga' => 'UA-53341066-1',
  'googlemap' => '',
  'gmzoom' => '15',
  'gzip' => 0,
  'partnerdown' => 0,
  'conduser' => 0,
  'wwwprefix' => 'http://chongiatot.tk',
  'imgprefix' => 'http://chongiatot.tk',
);
?>