<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Naver.com contacts importer.

You may not reprint or redistribute this code without permission from Lunarsys Solutions.

Copyright 2009 Lunarsys Solutions. All Rights Reserved
WWW: http://www.lunarsys.com
********************************************************************************/
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['naver'] = array('type'=>'abi', 'label'=>'Naver.com', 'class'=>'NaverImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//NaverImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class NaverImporter extends WebRequestor {

 	var $CONTACT_REGEX = "/<option\\s+value='\\d+'[^>]*>(.*?)\\s*&lt;(.*?)&gt;<\/option>/ims";

	//@api
	function fetchContacts ($loginemail, $password) {
	 	$parts = $this->getEmailParts ($loginemail);
	 	$login = $parts[0];
		$url = "http://nid.naver.com/nidlogin.login?url=http%3A%2F%2Fpda.naver.com%2F&svctype=2&postDataKey=&pda=1&id=".urlencode($login)."&pw=".urlencode($password)."&x=26&y=33";
		$html = $this->httpGet($url);
		if (strpos($html,"/nidlogin.login")!==FALSE) {
		 	$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
		
		$html = $this->httpGet("http://mail.naver.com/address/list.nhn?act=print_address");
		if (strpos($html,"all_addr_item")===FALSE) {
		 	$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find address list');
		}

		$cl = array();
        preg_match_all($this->CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
		foreach ($matches as $val) {
			$name = htmlentities2utf8(trim($val[1]));
			$email = htmlentities2utf8(trim($val[2]));
		 	if (abi_valid_email($email)) {
				$cl[] = new Contact($name,$email);
			}
		}
		return $cl;
	}	
}

//naver.com
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["naver.com"] = 'NaverImporter';


?>
