<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Terra.es/ole.com contacts importer

You may not reprint or redistribute this code without permission from Lunarsys Solutions.

Copyright 2009 Lunarsys Solutions. All Rights Reserved
WWW: http://www.lunarsys.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['terra'] = array('type'=>'abi', 'label'=>'Terra.es', 'class'=>'TerraImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//TerraImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class TerraImporter extends WebRequestor {
 
  	var $REDIRECT_REGEX = "/document\\.cookie=\"([^\"]*)\";.*?document\\.location='([^'\"]*)';/ims";
 	var $T_REGEX = "/&t=([^&\"']*)/ims";
 	var $CONTACT_REGEX = "/<tr\\s+class=\"listBody\\d*\".*?<td.*?<\/td>\\s*<td.*?<\/td>\\s*<td.*?<a[^>]*>\\s*([^<]*?)&nbsp;.*?<\/td>.*?doEmailContact\\('([^'\"]*)'\\)/ims";
 	var $PAGE_REGEX = "/P.gina (\\d+) de (\\d+)/ims";

	var $login;
	var $domain;
	var $t;
	var $homeuri;
	
	//@api
	function fetchContacts ($loginemail, $password) {
	 	$parts = $this->getEmailParts ($loginemail);
	 	$this->login = $parts[0];
	 	$this->domain = $parts[1];

		$form = new HttpForm;
		$action = "http://correo.terra.es/login_terra.cgi";
		if ("terra.es"==$this->domain) {
			$action = "http://correo.terra.es/login_terra.cgi";
		} else if ("ole.com"==$this->domain) {
			$action = "http://correo.terra.es/login_terra_ole.cgi";
		} else {
			$action = "http://correo.terra.es/tudominio/login_tudominio.cgi";
		}
		//$form->addField("referer", "http://poczta.interia.pl/");
		$form->addField("usera", $loginemail);
		$form->addField("user", $this->login);
		$form->addField("dominio", $this->domain);
		$form->addField("password", $password);
		$form->addField("entrar.x", "0");
		$form->addField("entrar.y", "0");
		$form->addField("_authtrkcde", "{#TRKCDE#}");
        $postData = $form->buildPostData();
    	$html = $this->httpPost($action, $postData);
		if (strpos($html,'Usuario/password incorrectos')>0) {
		 	$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}
    	
		// Add cookie and get redirect location
        if (preg_match($this->REDIRECT_REGEX,$html,$matches)==0) {
		 	$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find redirect location');
		}
		$cookie = $matches[1];
		$this->homeuri = $matches[2];
		$this->cookiejar->addCookie(new OzCookie($cookie,$this->lastUrl));
        if (preg_match($this->T_REGEX,$html,$matches)==0) {
		 	$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find t');
		}
		$this->t = $matches[1];
		
		$r = 1;
		$xurl = "/cp/ps/PSPab/viewContacts?d=".$this->domain."&u=".$this->login."&t=".$this->t."&ab=PAB%3A%2F%2F".$this->domain."%2F".$this->login."%2Fmain&rndum=".$r;
		$url = $this->makeAbsolute($this->homeuri, $xurl);
		$html = $this->httpGet($url);
	
		$emails = array();
		$cl = array();
		for ($page=1; $page<30; ) {
			// Increment to next page number
			$page++;

			// Extract contacts
			$found = 0;
	        preg_match_all($this->CONTACT_REGEX, $html, $matches, PREG_SET_ORDER);
			foreach ($matches as $val) {
			 	$name = htmlentities2utf8(trim($val[1]));
			 	$email = htmlentities2utf8(trim($val[2]));
			 	//Just in case we get stuck in loop
				if (!isset($emails[$email])) {
					$emails[$email]=1;
				 	if (abi_valid_email($email)) $cl[] = new Contact($name,$email);
				 	$found++;
				}
			}
			if ($found==0)
				break;
				
			// If we're in the last page, then abort.
			// Find next page of contacts if any
	        if (preg_match($this->PAGE_REGEX,$html,$matches)==0)
				break;
			$curPage = $matches[1];
			$totalPages = $matches[2];
			if ($curPage==$totalPages)
				break;

			// Else find next page to extract
			$form = ls_extract_form_by_name($html,"viewContactsForm");
			if ($form==null) {
			 	$this->close();
				return abi_set_error(_ABI_FAILED,'Cannot find contacts form');
			}
			$form->setField("page", $page);
			$form->setField("nameFilter", "*");
			$form->setField("categoryFilter", "All");
	        $postData = $form->buildPostData();
	    	$html = $this->httpPost($form->action, $postData);
		}

		return $cl;		
	}
		

}


//terra.es (release date: 15 June 2008)
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["terra.es"] = 'TerraImporter';
$_DOMAIN_IMPORTERS["ole.com"] = 'TerraImporter';
$_DOMAIN_IMPORTERS["tudominio.com"] = 'TerraImporter';
$_DOMAIN_IMPORTERS["tudominio.es"] = 'TerraImporter';
$_DOMAIN_IMPORTERS["tudominio.org"] = 'TerraImporter';

?>
