<?php
/********************************************************************************
DO NOT EDIT THIS FILE!

Yandex.ru contacts importer.

Note that mail.ru returns characters encoded in windows-1251 encoding.
This script tries to perform the conversion to utf-8 if iconv library is available,
but does not perform any encoding if the library is not available.

You may not reprint or redistribute this code without permission from Lunarsys Solutions.

Copyright 2009 Lunarsys Solutions. All Rights Reserved
WWW: http://www.lunarsys.com
********************************************************************************/
//include_once(dirname(__FILE__).'/abimporter.php');
if (!defined('__ABI')) die('Please include abi.php to use this importer!');

global $_OZ_SERVICES;
$_OZ_SERVICES['yandex'] = array('type'=>'abi', 'label'=>'Yandex', 'class'=>'YandexImporter');

/////////////////////////////////////////////////////////////////////////////////////////
//YandexImporter
/////////////////////////////////////////////////////////////////////////////////////////
//@api
class YandexImporter extends WebRequestor {

	//@api
	function logout()  {
		$this->httpGet("http://passport.yandex.ru/passport?mode=logout&retpath=http%3A%2F%2Fwww.yandex.ru%2F");
	}
 
	//@api
	function fetchContacts ($loginemail, $password) {

		
	 	$parts = $this->getEmailParts ($loginemail);
	 	$login = $parts[0];
	 	//$domain = $parts[1];

		$html = $this->httpGet("http://passport.yandex.ru/passport?mode=auth&retpath=http%3A%2F%2Fmail%2Eyandex%2Eru%2Fclassic%2Fabook%5Fexport");
		$form = ls_extract_form_by_name($html,"MainLogin");
		if ($form == null) {
		 	$this->close();
			return abi_set_error(_ABI_FAILED,'Cannot find login form');
		}
		$form->setField("login", $login);
		$form->setField("passwd", $password);
		$form->setField("In", "1"); // Some russian text
		$form->addField("_authtrkcde", "{#TRKCDE#}");
		$postData = $form->buildPostData();
		$html = $this->httpPost($form->action, $postData);
		if (strpos($html,"<img src=\"/images/i32attention.gif\"")!=false) {
		 	$this->close();
			return abi_set_error(_ABI_AUTHENTICATION_FAILED,'Bad user name or password');
		}

		$form = new HttpForm;
		// 0=Outlook Express
		// 1=Microsoft Outlook
		// 2=Mozilla Thunderbird
		$form->addField("tp", "1");
		// 1=russian
		// 0=english
		$form->addField("rus", "0");
		$postData = $form->buildPostData();
		$html = $this->httpPost("/classic/action_abook_export", $postData);

		$res = abi_extract_outlook_csv($html);
	 	$this->close();
		return $res;
	}	
}


// yandex.ru
global $_DOMAIN_IMPORTERS;
$_DOMAIN_IMPORTERS["yandex.ru"] = 'YandexImporter';

?>
